name: Build and Upload Artifacts on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore wslinternals.sln

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore wslinternals.sln

      - name: Publish x86_64
        run: |
          dotnet publish --configuration Release --no-build --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/x64 wslinternals.sln

      - name: Publish arm64
        run: |
          dotnet publish --configuration Release --no-build --runtime win-arm64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/arm64 wslinternals.sln

      - name: Upload x86_64 Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wslinternals-x64
          path: ./publish/x64/

      - name: Upload arm64 Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wslinternals-arm64
          path: ./publish/arm64/