name: Update Winget Manifest

on:
  release:
    types: [published]
  workflow_dispatch:    

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Install winget-create
      run: |
        Invoke-WebRequest -Uri 'https://aka.ms/wingetcreate/latest' -OutFile 'wingetcreate.exe'

    - name: Update Winget Manifest
      run: |
        $assets = '${{ toJson(github.event.release.assets) }}' | ConvertFrom-Json
        Write-Host "Release Event Assets: $assets"
        if ([string]::IsNullOrWhiteSpace($assets)) {
          Write-Host "No release event assets found, fetching from GitHub API"
          $release = Invoke-RestMethod -Uri https://api.github.com/repos/sirredbeard/wslinternals/releases/latest
          $assets = $release.assets
          $version = $release.tag_name
          Write-Host "GitHub API Assets: $assets"
          $url = ($assets | Where-Object { $_.name -eq "$version.zip" }).browser_download_url
          Write-Host "URL: $url"
          .\wingetcreate.exe update --urls $url --version $version sirredbeard.wslinternals --token "${{ secrets.WINGET_TOKEN }}" --submit
        } else {
          $version = ${{ github.event.release.tag_name }}
          $url = ($assets | Where-Object { $_.name -eq "$version.zip" }).browser_download_url
          Write-Host "URL: $url"
          .\wingetcreate.exe update --urls $url --version ${{ github.event.release.tag_name }} sirredbeard.wslinternals --token "${{ secrets.WINGET_TOKEN }}" --submit
        }
          